spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:litpath}
spring.datasource.username=${PGUSER:}
spring.datasource.password=${PGPASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


jwt.secret=${JWT_SECRET:}
jwt.expiration=${JWT_EXPIRATION:3600000}

google.books.api.key=${GOOGLE_BOOKS_API_KEY:}


server.port=${PORT:8080}