spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/litpath}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:8450}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


jwt.secret=${JWT_SECRET:223d4614737fe37b1ba36b02ece7f4196bf0f3d5d20cf1fa7256a67a82a45826}
jwt.expiration=${JWT_EXPIRATION:3600000}


google.books.api.key=${GOOGLE_BOOKS_API_KEY:AIzaSyDi5y5XqyZ6dNjCXST3MwGLA9392E8VsRg}

server.port=${PORT:8080}